pep_version: 2.0.0
sample_table: "sample_table.csv"
subsample_table: "subsample_table.csv"
sample_modifiers:
  derive:
    attributes: [assembly_file_path, coverage_path]
    sources:
      local_assembly: /media/mlawlor/work/210302_busco_for_mahek/data/{assembly_file}
      local_coverage: /media/mlawlor/work/210302_busco_for_mahek/data/{coverage}
      amarel_assembly: /scratch/mal456/from_mahek/{assembly_file}
      amarel_coverage: /scratch/mal456/from_mahek/{coverage}
